# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oG9iv8UngKd4km89_vBX1xVpq0eBg4ie
"""

import gradio as gr
import pandas as pd
import matplotlib.pyplot as plt

# Store energy data
energy_log = pd.DataFrame(columns=["Date", "Renewable", "Non_Renewable"])

# Function to update data and generate plots
def track_energy(date, renewable, non_renewable):
    global energy_log
    # Add new entry
    new_entry = pd.DataFrame([[date, renewable, non_renewable]], columns=energy_log.columns)
    energy_log = pd.concat([energy_log, new_entry], ignore_index=True)

    # Calculate totals
    energy_log["Total"] = energy_log["Renewable"] + energy_log["Non_Renewable"]
    energy_log["Renewable_%"] = (energy_log["Renewable"] / energy_log["Total"]) * 100

    # Plot energy usage
    fig, ax = plt.subplots(figsize=(8, 5))
    ax.plot(energy_log["Date"], energy_log["Renewable"], label="Renewable", marker='o', color='green')
    ax.plot(energy_log["Date"], energy_log["Non_Renewable"], label="Non-Renewable", marker='o', color='red')
    ax.set_title("Daily Energy Consumption")
    ax.set_xlabel("Date")
    ax.set_ylabel("kWh")
    ax.legend()
    ax.grid(True)

    return fig, energy_log.tail(5)

# Gradio interface
demo = gr.Interface(
    fn=track_energy,
    inputs=[
        gr.Textbox(label="Date (YYYY-MM-DD)"),
        gr.Number(label="Renewable Energy (kWh)"),
        gr.Number(label="Non-Renewable Energy (kWh)")
    ],
    outputs=[
        gr.Plot(label="Energy Usage Chart"),
        gr.Dataframe(label="Recent Entries")
    ],
    title="⚡ Green Energy Consumption Tracker",
    description="Log your daily energy usage and visualize your renewable vs non-renewable consumption."
)

demo.launch()